name: tilt_gradient_app
description: A Flutter app that displays a gradient effect responding to device tilt.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
